import Link from "next/link";
import { ExternalLink, Link2, Plus, Tags } from "lucide-react";
import { getCurrentMerchant } from "../../../lib/merchant";
import { createLinkAction, deleteLinkAction, toggleLinkAction } from "../actions";
import styles from "../management.module.css";

type Props={searchParams:Promise<{error?:string}>};
const linkTypes=["whatsapp","instagram","tiktok","maps","website","marketplace","reservation","custom"] as const;
const labels:Record<(typeof linkTypes)[number],string>={whatsapp:"WhatsApp",instagram:"Instagram",tiktok:"TikTok",maps:"Google Maps",website:"Website",marketplace:"Marketplace",reservation:"Reservasi",custom:"Link custom"};

export default async function LinksPage({searchParams}:Props){
  const {tenant,supabase}=await getCurrentMerchant();if(!tenant)return null;
  const [{data:links},{error}]=await Promise.all([supabase.from("custom_links").select("id,title,url,link_type,is_active").eq("tenant_id",tenant.id).order("sort_order"),searchParams]);
  return <main className={styles.page}><header className={styles.top}><Link className={styles.brand} href="/dashboard"><span>m</span>menuku</Link><nav><Link href="/dashboard">Dashboard</Link><Link href="/dashboard/menu">Menu</Link><Link href="/dashboard/categories">Kategori</Link><Link className={styles.active} href="/dashboard/links">Links</Link></nav><Link href={`/store/${tenant.slug}`} target="_blank">Lihat halaman</Link></header><section className={styles.content}><div className={styles.heading}><div><h1 className="display">Link bisnis</h1><p>Kumpulkan WhatsApp, sosial media, lokasi, dan tautan penting dalam satu halaman.</p></div></div>{error&&<p className={styles.notice}>{error}</p>}<div className={styles.grid}><article className={styles.formCard}><h2 className="display">Tambah link</h2><p>Gunakan URL lengkap agar pelanggan dapat membukanya dengan aman.</p><form className={styles.form} action={createLinkAction}><label>Jenis link<select name="linkType" defaultValue="whatsapp">{linkTypes.map(type=><option value={type} key={type}>{labels[type]}</option>)}</select></label><label>Judul link<input name="title" required maxLength={100} placeholder="Contoh: Chat kami di WhatsApp"/></label><label>URL tujuan<input name="url" type="url" required placeholder="https://..."/></label><button className={styles.submit} type="submit"><Plus size={16}/>Simpan link</button></form></article><article className={styles.listCard}><h2 className="display">Daftar link</h2><p>{links?.length??0} link tersimpan pada {tenant.name}</p>{links?.length?<div className={styles.list}>{links.map(item=><div className={styles.item} key={item.id}><span className={styles.itemIcon}><Link2 size={18}/></span><div className={styles.itemInfo}><b>{item.title}</b><small className={styles.url}>{item.url}</small><span className={item.is_active?styles.state:styles.inactive}>{item.is_active?labels[item.link_type as keyof typeof labels]||"Aktif":"Disembunyikan"}</span></div><a className={styles.openLink} href={item.url} target="_blank" rel="noopener noreferrer" aria-label={`Buka ${item.title}`}><ExternalLink size={15}/></a><div className={styles.itemActions}><form action={toggleLinkAction}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="active" value={String(item.is_active)}/><button>{item.is_active?"Sembunyikan":"Tampilkan"}</button></form><form action={deleteLinkAction}><input type="hidden" name="id" value={item.id}/><button className={styles.danger}>Hapus</button></form></div></div>)}</div>:<div className={styles.empty}><Tags size={25}/><p>Belum ada link. Tambahkan WhatsApp, sosial media, atau lokasi bisnismu.</p></div>}</article></div></section></main>;
}
