import Link from "next/link";
import { ArrowRight, BarChart3, Check, Eye, Instagram, LayoutTemplate, MapPin, MenuSquare, QrCode, Search, Share2, Sparkles } from "lucide-react";
import styles from "./home.module.css";

const plans = [
  { name:"Free", price:"Rp0", note:"Untuk mulai menampilkan menu", features:["1 halaman katalog","Maks. 15 produk","Link WhatsApp & sosial","QR code dasar"], href:"/register?plan=free", cta:"Mulai gratis" },
  { name:"Premium", price:"Rp29rb", note:"per bulan · untuk bisnis berkembang", features:["Produk tanpa batas","Tema dan warna brand","Analytics lengkap","Hilangkan branding Menuku"], href:"/register?plan=premium", cta:"Pilih Premium", featured:true },
  { name:"Business", price:"Rp79rb", note:"per bulan · untuk tim", features:["Semua fitur Premium","3 anggota tim","Custom domain","Dukungan prioritas"], href:"/register?plan=business", cta:"Pilih Business" },
];

export default function Home() {
  return <main className={styles.page}>
    <header className={styles.nav}><Link href="/" className={styles.brand}><span>m</span> menuku</Link><nav><a href="#fitur">Fitur</a><a href="#harga">Harga</a><a href="#cara">Cara kerja</a></nav><div><Link href="/login">Masuk</Link><Link href="/register" className={styles.navCta}>Buat menu gratis <ArrowRight size={15}/></Link></div></header>
    <section className={styles.hero}><div className={styles.copy}><p className={styles.kicker}><Sparkles size={14}/> Katalog digital untuk bisnis kuliner</p><h1 className="display">Menu kamu, <em>satu link</em> yang mudah dibagikan.</h1><p>Bangun halaman menu yang cantik, letakkan WhatsApp, lokasi, dan sosial media dalam satu tempat. Tanpa perlu coding.</p><div className={styles.actions}><Link href="/register" className={styles.cta}>Buat menu gratis <ArrowRight size={17}/></Link><Link href="/store/kopitemu" className={styles.demo}>Lihat contoh <Eye size={16}/></Link></div><small><Check size={14}/> Gratis selamanya · Tanpa kartu kredit</small></div><div className={styles.visual}><i className={styles.aura}/><div className={styles.phone}><div className={styles.phoneBar}>9:41 <span/></div><div className={styles.cover}><b><i/> Buka sampai 22.00</b><Share2 size={15}/></div><div className={styles.profile}><strong>KT</strong><div><h3 className="display">Kopi Temu</h3><p><MapPin size={9}/> Kemang, Jakarta</p></div></div><div className={styles.wa}>Pesan via WhatsApp <ArrowRight size={13}/></div><p className={styles.label}>FAVORIT MINGGU INI</p><div className={styles.cards}><article><MenuSquare size={22}/><b>Kopi Susu Aren</b><small>Rp24.000</small></article><article><MenuSquare size={22}/><b>Matcha Cloud</b><small>Rp35.000</small></article></div><div className={styles.search}><Search size={14}/> Cari menu...</div></div><div className={styles.stats}><BarChart3/><div><b>1.284</b><span>kunjungan minggu ini</span></div><strong>+18%</strong></div></div></section>
    <section className={styles.trust}><p>Untuk menyajikan menu yang lebih mudah ditemukan</p><div><span>KEDAI KITA</span><span>NASI TEMAN</span><span>REMPAH SORE</span><span>BAKE & BLOOM</span><span>WARMINDO</span></div></section>
    <section id="fitur" className={styles.features}><header><p className={styles.kicker}>SEMUA DALAM SATU TEMPAT</p><h2 className="display">Lebih dari sekadar daftar menu.</h2><p>Halaman yang dirancang supaya pelanggan mendapat informasi yang mereka butuhkan dengan cepat.</p></header><div className={styles.featureGrid}><article><span><MenuSquare/></span><h3 className="display">Katalog yang enak dilihat</h3><p>Foto produk, kategori, pencarian, harga promo, dan status habis yang jelas.</p></article><article><span><QrCode/></span><h3 className="display">Bagikan di mana saja</h3><p>Satu link dan QR code untuk meja, Instagram, WhatsApp, atau Google.</p></article><article><span><BarChart3/></span><h3 className="display">Analytics sederhana</h3><p>Lihat menu populer, sumber kunjungan, dan link yang paling banyak diklik.</p></article><article><span><LayoutTemplate/></span><h3 className="display">Terasa seperti brand kamu</h3><p>Pilih warna, tema, bentuk tombol, dan layout yang sesuai bisnismu.</p></article></div></section>
    <section id="cara" className={styles.steps}><div><p className={styles.kicker}>MULAI DALAM HITUNGAN MENIT</p><h2 className="display">Dari dapur ke layar pelanggan.</h2></div><ol><li><b>01</b><div><h3>Buat profil bisnismu</h3><p>Tentukan nama, alamat, jam buka, dan alamat halaman unik.</p></div></li><li><b>02</b><div><h3>Masukkan menu & link</h3><p>Tambah produk, foto, WhatsApp, Instagram, dan lokasi.</p></div></li><li><b>03</b><div><h3>Bagikan ke pelanggan</h3><p>Unduh QR code atau taruh link di semua kanal bisnismu.</p></div></li></ol></section>
    <section id="harga" className={styles.pricing}><header><p className={styles.kicker}>PILIH SESUAI KEBUTUHAN</p><h2 className="display">Mulai kecil, berkembang kapan saja.</h2><p>Semua paket dapat dimulai gratis. Upgrade ketika bisnismu membutuhkan lebih banyak.</p></header><div className={styles.planGrid}>{plans.map((plan) => <article key={plan.name} className={plan.featured ? styles.featuredPlan : styles.plan}>{plan.featured && <i>Paling populer</i>}<h3 className="display">{plan.name}</h3><div className={styles.price}><b>{plan.price}</b>{plan.name !== "Free" && <span>/bulan</span>}</div><p>{plan.note}</p><Link href={plan.href}>{plan.cta} <ArrowRight size={15}/></Link><ul>{plan.features.map((feature) => <li key={feature}><Check size={15}/>{feature}</li>)}</ul></article>)}</div><small className={styles.note}>Pilihan paket disimpan saat pendaftaran. Pembayaran/upgrade otomatis dapat diaktifkan setelah integrasi payment gateway ditambahkan.</small></section>
    <section className={styles.final}><div><p className={styles.kicker}>SIAP UNTUK MULAI?</p><h2 className="display">Buat halaman menu yang pantas untuk bisnismu.</h2><p>Gratis, cepat, dan siap dibagikan hari ini.</p><Link href="/register" className={styles.cta}>Buat menu gratis <ArrowRight size={17}/></Link></div><aside><MapPin/><Instagram/><QrCode/></aside></section>
    <footer className={styles.footer}><Link href="/" className={styles.brand}><span>m</span> menuku</Link><p>© 2026 Menuku. Katalog digital untuk bisnis kuliner.</p><Link href="/login">Masuk</Link></footer>
  </main>;
}
