export type Tenant = {
  id: string;
  owner_id: string;
  name: string;
  slug: string;
  description: string | null;
  business_type: string | null;
  logo_url: string | null;
  banner_url: string | null;
  promo_enabled: boolean;
  promo_title: string | null;
  promo_description: string | null;
  promo_image_url: string | null;
  promo_link_url: string | null;
  whatsapp: string | null;
  instagram: string | null;
  address: string | null;
  maps_url: string | null;
  opening_hours: unknown;
  is_published: boolean;
  is_active: boolean;
  primary_color: string;
  background_color: string;
  layout_type: string;
  show_price: boolean;
  show_address: boolean;
  show_opening_hours: boolean;
  plan: "free" | "premium" | "business";
};
